tried to shift to slack-machie
OWASP-BLT/BLT-Lettuce pull request #46
Opened 2024-06-05 19:05 UTC by Sarthak5598

2024-06-06 18:16 UTC, arkid15r requested changes

2024-06-06 18:19 UTC, Sarthak5598 commented
Thank you @arkid15r for the suggestions

2024-06-07 16:18 UTC, Sarthak5598 commented on manifest.yaml
> +      - app_mentions:read
changed it thank you!

2024-06-07 16:34 UTC, arkid15r approved these changes
LGTM

2024-06-07 16:34 UTC, arkid15r commented on manifest.yaml
> +      - im:read
Just sorted it:
```suggestion
      - channels:read
      - commands
      - groups:read
      - im:read
      - mpim:read
      - users:read
```

2024-06-07 16:48 UTC, Sarthak5598 commented
Thank you @arkid15r

2024-06-07 16:48 UTC, merged